version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    groups:
      cargo-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
